[package]
name = "boatbomber/boattest"
description = "Boat's TrulyEasySimpleTesting - A Luau unit testing framework. Inspired by Elttob's FusionCI"
version = "0.1.1"
license = "MIT"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]
